### ISSUE TITLE
Conversion of transparent png to jxr is not working

### ISSUE THREAD

**Issue by bjg2** [courtneypattison/gulp-jpeg-xr#2]
Can you please add `-truecolors` to line 28 in index.js (making it `const nconvert = cp.spawn('nconvert', ['-truecolors', '-out', 'jxr', '-overwrite', '-o', tmpOutFilePath, '-quiet', tmpInFilePath]);`), or to add it as an option? Currently it blocks me from using this library, as it does not work for converting transparent png-s...

**Comment by courtneypattison** [comment]
Hey @bjg2, thank you for the feature request! I just published v1.1.0 with an options parameter. Run `jxr(['-truecolours'])` for transparent pngs. Please let me know if it doesn't work!

**Comment by bjg2** [comment]
it does work now. thanks!
